MyDjango/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    path('',include('index.urls',namespace='index')),
]

index/urls.py
from django.conf.urls import url
from . import views
app_name = 'index'
urlpatterns=[
    # 主页
    url(r'^$',views.index,name='index'),
    #显示所有主题
    url(r'^topics/$',views.topics,name='topics'),
    #特定主题的页面
    # /(?P<topic_id>\d+)/ )与包含在两个斜杠内的整数匹配，并将这个整数存储在一个名为topic_id时掺中。
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # 用于添加新主题的网页
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # 用于添加新条目的页面
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # 用于编辑条目的页面
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
    url(r'^del_topic/$',views.del_topic,name='del_topic'),
    url(r'^del_entry/$',views.del_entry,name='del_entry'),
    url(r'^edit_topic/(?P<topic_id>\d+)/$', views.edit_topic, name='edit_topic'),
]

users/urls.py
from django.contrib.auth.views import LoginView
from django.conf.urls import url

from . import views

app_name = 'users'
 
urlpatterns = [
    #登录页面
	#url(r'^login/$', login, {'template_name': 'users/login.html'}, name = 'login'),
	#url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name="login"),
    url('login1.html',views.loginView,name='login1'),
    # 注销
    url(r'^logout/$', views.logout_view, name='logout'),
    # 注册页面
    url(r'register.html', views.register, name='register'),

    url('setpassword.html',views.setpasswordView,name='setpassword'),
    url('findpassword.html',views.findpassword,name='findpassword'),
    url('home.html',views.homeView,name='home'),

]

index/templates/index/11.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style type="text/css">
        *{
            padding: 0%;
            margin: 0%;
        }

        html, body{
            background:#f2f2f2;
        }

        .calendar{
            margin: 45px;
            width: 350px;
            height: 300px;
            background: white;
            box-shadow: 0px 1px 1px rgba(0,0,0,.1);
        }

        .title{
            height: 70px;
            border-bottom: 1px solid rgba(0,0,0,.1);
            position: relative;
            text-align: center;
        }

        #calendar-title{
            font-size: 25px;
            text-transform: uppercase;
            font-family: Arial, Helvetica, sans-serif;
            padding: 14px 0 0 0;
        }

        #calendar-year{
            font-size: 15px;
            font-family: Arial, Helvetica, sans-serif;
            font-weight: normal;
        }

        #pre{
            position: absolute;
            top: 0px;
            left: 0px;
            background: url(prev.png) no-repeat 50% 50%;

            /*没规定大小时，图片显示 0X0*/
            width: 60px;
            height: 70px;

        }

        #next{
            position: absolute;
            top: 0px;
            right: 0px;
            background: url(next.png) no-repeat 50% 50%;
            width: 60px;
            height: 70px;
        }

        .body-list ul{
            font-size: 14px;
            font-family: Arial, Helvetica, sans-serif;
            font-weight: bold;
            width: 100%;
            box-sizing: border-box;

        }

        .body-list ul li{
            list-style: none;
            /*
            display:inline-block;
            width: 13.3%;
            */

            /*100/7 = 14.28%*/
            display: block;
            width: 14.28%;
            float: left;

            /*规定行高，垂直居中*/
            height: 36px;
            line-height: 36px;
            box-sizing: border-box;
            text-align: center;

        }


        .green{
            color:#6ac13c;
        }

        .lightgrey{ /*浅灰色显示过去的日期*/
	        color:#a8a8a8;
        }
        .darkgrey{ /*深灰色显示将来的日期*/
	        color:#565656;
        }

        /*日期当天用绿色背景绿色文字加以显示*/
        .greenbox{
            border: 1px solid #6ac13c;
            background: #e9f8df;
        }
    </style>
</head>
<body>
    <div class="calendar">
        <div class="title">
            <h1 class="green" id="calendar-title">Month</h1>
            <h2 class="green" id="calendar-year">Year</h2>
            <a href="" id="pre"></a>
            <a href="" id="next"></a>
        </div>

        <div class="body">
            <div class="lightgrey body-list">
                <ul>
                    <li>SUN</li>
                    <li>MON</li>
                    <li>TUE</li>
                    <li>WED</li>
                    <li>THU</li>
                    <li>FRI</li>
                    <li>SAT</li>

                </ul>

            </div>

            <div class="darkgrey body-list">
                <ul id="days">

                </ul>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        var month_olypic = [31,29,31,30,31,30,31,31,30,31,30,31];//闰年每个月份的天数
        var month_normal = [31,28,31,30,31,30,31,31,30,31,30,31];
        var month_name =["January","Febrary","March","April","May","June","July","Auguest","September","October","November","December"];
        //获取以上各个部分的id
        var holder = document.getElementById("days");
        var prev = document.getElementById("prev");
        var next = document.getElementById("next");
        var ctitle = document.getElementById("calendar-title");
        var cyear = document.getElementById("calendar-year");
        //获取当天的年月日
        var my_date = new Date();
        var my_year = my_date.getFullYear();//获取年份
        var my_month = my_date.getMonth(); //获取月份，一月份的下标为0
        var my_day = my_date.getDate();//获取当前日期

        //根据年月获取当月第一天是周几
        function dayStart(month,year){
            var tmpDate = new Date(year, month, 1);
            return (tmpDate.getDay());
        }
        //根据年份判断某月有多少天(11,2018),表示2018年12月
        function daysMonth(month, year){
            var tmp1 = year % 4;
            var tmp2 = year % 100;
            var tmp3 = year % 400;

            if((tmp1 == 0 && tmp2 != 0) || (tmp3 == 0)){
                return (month_olypic[month]);//闰年
            }else{
                return (month_normal[month]);//非闰年
            }
        }
        //js实现str插入li+class,不要忘了用innerhtml进行插入
        function refreshDate(){
            var str = "";
            //计算当月的天数和每月第一天都是周几，day_month和day_year都从上面获得
            var totalDay = daysMonth(my_month,my_year);
            var firstDay = dayStart(my_month, my_year);
            //添加每个月的空白部分
            for(var i = 0; i < firstDay; i++){
                str += "<li>"+"</li>";
            }

            //从一号开始添加知道totalDay，并为pre，next和当天添加样式
            var myclass;
            for(var i = 1; i <= totalDay; i++){
                //三种情况年份小，年分相等月份小，年月相等，天数小
                //点击pre和next之后，my_month和my_year会发生变化，将其与现在的直接获取的再进行比较
                //i与my_day进行比较,pre和next变化时，my_day是不变的
                console.log(my_year+" "+my_month+" "+my_day);
                console.log(my_date.getFullYear()+" "+my_date.getMonth()+" "+my_date.getDay());
                if((my_year < my_date.getFullYear())||(my_year == my_date.getFullYear() && my_month < my_date.getMonth()) || (my_year == my_date.getFullYear() && my_month == my_date.getMonth() && i < my_day)){
                    myclass = " class='lightgrey'";
                }else if(my_year == my_date.getFullYear() && my_month == my_date.getMonth() && i == my_day){
                    myclass = "class = 'green greenbox'";
                }else{
                    myclass = "class = 'darkgrey'";
                }
                str += "<li "+myclass+">"+i+"</li>";
            }
            holder.innerHTML = str;
            ctitle.innerHTML = month_name[my_month];
            cyear.innerHTML = my_year;
        }
        //调用refreshDate()函数，日历才会出现
        refreshDate();
        //实现onclick向前或向后移动
        pre.onclick = function(e){
            e.preventDefault();
            my_month--;
            if(my_month < 0){
                my_year--;
                my_month = 11; //即12月份
            }
            refreshDate();
        }

        next.onclick = function(e){
            e.preventDefault();
            my_month++;
            if(my_month > 11){
                my_month = 0;
                my_year++;
            }
            refreshDate();
        }
    </script>
</body>
</html>

index/templates/index/base.html
{% load bootstrap3 %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>学习笔记</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
   <!-- <style type="text/css">
        .bg{background-color: khaki}
        .mk{padding-top: 16px;color: dimgray}
    </style>-->
    <script type="text/javascript">
		function start(){
			var now=new Date();
			var hr=now.getHours();
			var min=now.getMinutes();
			var sec=now.getSeconds();
			var clocktext="Time："+hr+":"+min+":"+sec;
			var timeTD=document.getElementById("timeArea");
			timeTD.innerText=clocktext;
		}
		window.setInterval("start()",1000);
	</script>
</head>
<body style="background-image: url({% static 'timg.jpg' %});background-size:100% 150%;">
 <div class="bg">
   <!-- Static navbar -->
   <!--nav表示导航链接-->
   <nav class="navbar navbar-default navbar-static-top">
       <div class="container">
           <div class="navbar-header">
               <button type="button" class="navbar-toggle collapsed"
                   data-toggle="collapse" data-target="#navbar"
                   aria-expanded="false" aria-controls="navbar">
               </button>
               <a class="navbar-brand" href="{% url 'index:index' %}">Learning Log</a>
           </div>

           <div id="navbar" class="navbar-collapse collapse">
               <ul class="nav navbar-nav">
                   <li><a href="{% url 'index:topics' %}">Topics</a></li>
               </ul>

               <ul class="nav navbar-nav navbar-right">
                   {% if user.is_authenticated %}

                     <!--  <li id="timeArea" class="mk"></li>-->
                       <li><a>你好,{{ user.username }}.</a></li>
                       <li><a href="{% url 'users:home' %}">个人中心</a> </li>
                       <li><a href="{% url 'users:logout' %}">注销</a> </li>
                       <li><a href="{% url 'users:setpassword' %}">修改密码</a> </li>
                   {% else %}
                       <li><a href="http://127.0.0.1:8000/admin">管理员</a> </li>
                       <li><a href="{% url 'users:register' %}">注册</a></li>
                       <li><a href="{% url 'users:login1' %}">登录</a> </li>

                       <li></li>
                   {% endif %}
               </ul>
           </div><!--/.nav-collapse-->
       </div>

   </nav>
   <div class="container">
       <div class="page-header">
           {% block header %}
           {% endblock header %}

       </div>
       <div>
           {% block content %}
           {% endblock content %}
       </div>
   </div>
 </div>
</body>
</html>

index/templates/index/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
   {% extends "index/base.html" %}
   {% load bootstrap3 %}
   {% block header %}
	<h2>Edit a entry</h2>
{% endblock header%}
   {% block content %}
       <h4><a href="{% url 'index:topic' topic.id %}">{{ topic }}</a> </h4>
       <p>Edit entry:</p>

       <form action="{% url 'index:edit_entry' entry.id %}" method="post",class="form">
         {% csrf_token %}
         {% bootstrap_form form %}
         {% buttons %}
             <button name="submit" class="btn btn-primary">Save Edit</button>
         {% endbuttons %}

       </form>
   {% endblock content %}
</body>
</html>

index/templates/index/edit_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改话题</title>
</head>
<body>
   {% extends "index/base.html" %}
   {% load bootstrap3 %}
   {% block header %}
	<h2>Edit a topic</h2>
{% endblock header%}
   {% block content %}

       <p>Edit topic:</p>

       <form action="{% url 'index:edit_topic' topic.id %}" method="post",class="form">
         {% csrf_token %}
         {% bootstrap_form form %}
         {% buttons %}
             <button name="submit" class="btn btn-primary">Save Edit</button>
         {% endbuttons %}

       </form>
   {% endblock content %}
</body>
</html>

index/templates/index/index.html
{%  extends "index/base.html" %}
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>

    <style type="text/css">

        .zt{font-family:"HanziPen SC",serif}
    </style>
</head>
<body>

  {% block header %}
      <div class="jumbotron">

         <h1 class="zt">Track your learning.</h1>
      </div>
  {% endblock header %}
  {% block content %}
      <h3 class="zt">
         <a href="{% url 'users:register' %}">Register an account</a> to make your own Learning Log,and list the topics you're learning about.
      </h3>
      <h3>
         Whenever you learn something new about a topic, make an entry summarizing what you've learned.
      </h3>
  {% endblock content %}
</body>
</html>

index/templates/index/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> 写笔记</title>
</head>
<body>
{% extends "index/base.html" %}
{% load bootstrap3 %}

{% block header %}
	<h2>Add a new entry:</h2>
{% endblock header%}

{% block content %}
	<h3><a href="{% url 'index:topic' topic.id %}">{{ topic }}</a></h3>

	<form action = "{% url 'index:new_entry' topic.id %}" method='post'
		class="form">

		{% csrf_token %}	<!-- #防御csrf攻击的方式-->
		{{ form.as_p }}		<!-- #把form表单在前端页面渲染成p标签的形式展示，此外还有as_ul,as_table等 -->

		{% buttons %}
			<button name='submit' class="btn btn-primary">add entry</button>
		{% endbuttons%}

    </form>

{% endblock content%}

</body>
</html>

index/templates/index/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>写主题</title>
    <style type="text/css">

    </style>
</head>
<body>

{% extends 'index/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

 {% block content %}

     <!--实参action高诉服务器将提交的表单数据发送到new_topic-->
     <form action="{% url 'index:new_topic' %} " method="post" class="form">
         <!--来防止攻击者利用表单来获取对服务器未经授权的访问-->
         <!--修饰符as_p让Django以段落格式渲染所有表单元素-->
         {% csrf_token %}
         {% bootstrap_form form %}
         {% buttons %}
             <button name="submit" class="btn btn-primary">Add Topic</button>
         {% endbuttons %}

     </form>

 {% endblock content %}

</body>
</html>

index/templates/index/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>topic</title>
</head>
<body>
    {% extends 'index/base.html' %}
     {% load staticfiles %}
    {% block header %}
        <h2>{{Topic}}</h2>
    {% endblock header %}

    {% block content %}
        <h4>
           <a href="{% url 'index:new_entry' topic.id %}">add new entry</a>
        </h4>

        {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'index:edit_entry' entry.id %}"> <span class="glyphicon glyphicon-pencil" style="margin-left: 2px"></span></a>
                    </small>
                     <a name="delete" href="javascript:" onclick="del_column(this, {{ entry.id }})">
                    <span class="glyphicon glyphicon-trash" style="margin-left:20px; " title="暂未开放此功能l" ></span>
                   </a>
                </h3>
            </div>
           <div class="panel-body">
               {{ entry.text|linebreaks }}
           </div>
        </div>
         {% empty %}
            There are no entries for this topic yet.
        {% endfor %}
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">

function del_column(the, entry_id){
    var name = $(the).parents("tr").children("td").eq(1).text();
    layer.open({
    type: 1,
    skin: "layui-layer-rim",
    area: ["400px", "200px"],
    title: "删除栏目",
    content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除{'+name+'}栏目</p></div>',
    btn:['确定', '取消'],
    yes: function(){
        $.ajax({
        url: '{% url 'index:del_entry' %}',
        type:"POST",
        data: {"entry_id": entry_id},
        success: function(e){
            if(e=="1"){
            parent.location.reload();
            layer.msg("has been deleted.");
        }else{
            layer.msg("删除失败");
        }
        },
        })
    },
    });
}

</script>
    {% endblock content %}
</body>
</html>

index/templates/index/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topics</title>
     <style type="text/css">
         a:link{color: grey}

         a:visited{color: dimgrey}
         a:hover{color: darkgray }
         a:active{color: dimgray}
     </style>
</head>
<body>
    {% extends "index/base.html"%}
    {% load staticfiles %}

    {% block header %}
        <h2>Topics</h2>
    {% endblock header %}

    {% block content %}

       <div>

        <table class="table table-hover" >
          <tr>
            <td>序号</td>
            <td>话题</td>
            <td>操作</td>
              <td></td>
          </tr>
            {% for topic in topics %}
               <tr>
                  <td>{{ topic.id }}</td>
                  <td>

                       <a href="{% url 'index:topic' topic.id %}" style="text-decoration: none">{{ topic }}</a>
                  </td>
               <td>
                    <a href="{% url 'index:edit_topic' topic.id %}">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>

                  <a name="delete" href="javascript:" onclick="show()">
                    <span class="glyphicon glyphicon-trash" style="margin-left:20px;" title="暂未开放此功能"></span>
                   </a>


               </td>

               </tr>

            {% empty %}
                <li>No topics have been added yet.</li>

            {% endfor %}


        </table>
        <h4 align="right"><a href="{% url 'index:new_topic' %}" style="text-decoration: none" >Add new topic </a></h4>
       </div>



<script type="text/javascript">

function del_column(the, topic_id){
    var name = $(the).parents("tr").children("td").eq(1).text();
    layer.open({
    type: 1,
    skin: "layui-layer-rim",
    area: ["400px", "200px"],
    title: "删除栏目",
    content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除{'+name+'}栏目</p></div>',
    btn:['确定', '取消'],
    yes: function(){
        $.ajax({
        url: '{% url 'index:del_topic' %}',
        type:"POST",
        data: {"topic_id": topic_id},
        success: function(e){
            if(e=="1"){
            parent.location.reload();
            layer.msg("has been deleted.");
        }else{
            layer.msg("删除失败");
        }
        },
        })
    },
    });
}
function show() {
  alert('您不是超级用户');

}
</script>
    {% endblock content %}


</body>
</html>